### ISSUE TITLE
[BUG] "Invalid Request. Dumping the Response" error when running command on slack

### ISSUE THREAD

**Issue by markjayniel** [infracloudio/botkube#105]
Hi - I am currently testing and playing around with this. Everytime I run "@botkube get pods" on slack, it does not give any response. I looked at the logs and I get below error:
```
INFO[2019-06-13T18:46:11Z] Invalid request. Dumping the response        
INFO[2019-06-13T18:51:43Z] Invalid request. Dumping the response        
INFO[2019-06-13T18:51:52Z] Invalid request. Dumping the response        
INFO[2019-06-13T18:53:53Z] Invalid request. Dumping the response        
INFO[2019-06-13T18:55:20Z] Invalid request. Dumping the response        
INFO[2019-06-13T18:55:31Z] Invalid request. Dumping the response  
```      
I ran both helm and deploy all yaml file kubernetes manifests and both gave the same error. Am I missing anything? I setup the slack channel, the token, cluster name, and "allowkubectl: true" so I assume everything is setup?

If I enable events, I can see it populating in slack but slack can't seem to communicate correctly to the kubernetes cluster. Am I missing something?

**Comment by markjayniel** [comment]
ahhh found the fix! the problem was the slack channel. I was adding "#" on slack name when its not really needed. 

```
  communications:
    # Settings for Slack
    slack:
      enabled: true
      channel: '#kubernetes'
      token: '<secret token>'
```
when it should be:
```
  communications:
    # Settings for Slack
    slack:
      enabled: true
      channel: 'kubernetes'
      token: '<secret token>'
```

**Comment by thorro** [comment]
Not an obvious error, maybe docs should reflect that.
