### ISSUE TITLE
Ability to disable config file watcher

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#150]
**Is your feature request related to a problem? Please describe.**
One should be able to disable auto restart on config file change through the BotKube configuration flags.

**Describe the solution you'd like**
We can add a flag like - `settings.configWatcher=true/false` to enable/disable this feature.

**Comment by aananthraj** [comment]
Looks cool to overcome bugs 👍 and get us unblocked for 0.9.0
