### ISSUE TITLE
Run as non-root

### ISSUE THREAD

**Issue by rajinator** [infracloudio/botkube#161]
**Is your feature request related to a problem? Please describe.**
Currently the container runs as root, which is not ideal for security.

```bash
kubectl exec -it -n botkube botkube-597bc97cdf-pqx6v sh
/ # id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
/ # whoami
root
```

**Describe the solution you'd like**
For a more secure deployment, make changes to Dockerfile, k8s manifest and helm chart, to run as non root.

**Additional context**
Might add a PR with example code soon.

**Comment by PrasadG193** [comment]
@aananthraj please let others know if you have picked up or want to work on an issue to avoid work duplication :slightly_smiling_face: You can assign task to yourself that will help in tracking the issue

**Comment by aananthraj** [comment]
Sure, will let others know 👍

> You can assign task to yourself that will help in tracking the issue.

I guess I dont have enough privileges to assign an issue to myself 😅. 
Will ask one of you to do so 👍
