### ISSUE TITLE
[BUG] Botkube sends slack notifications multiple times for an event

### ISSUE THREAD

**Issue by mstrYoda** [infracloudio/botkube#181]
**Describe the bug**
I've delete a statefulset via helm and slack notification sent by botkube. But I watch the channel and it keeps sending notifications.

Botkube puts the time to the footer of notification as follows:
BotKube | Today at 1:25 PM

But even latest notifications at 2:14 PM contain same footer "BotKube | Today at 1:25 PM".

When I type `kubectl get events` there is not any event which recently happened to send 
notification to slack.

**To Reproduce**
I am not sure how to reproduce this behavior.

**Expected behavior**
It should only send one time notification.

**Screenshots**
<img width="532" alt="Screen Shot 2019-09-17 at 14 24 08" src="https://user-images.githubusercontent.com/12763626/65037708-f148b680-d956-11e9-94b0-e6bee17c02e3.png">
<img width="1100" alt="Screen Shot 2019-09-17 at 14 24 14" src="https://user-images.githubusercontent.com/12763626/65038100-d75ba380-d957-11e9-8b13-d7b223a9d176.png">

**Comment by PrasadG193** [comment]
@mstrYoda What version of BotKube you are using? You can get version with `@BotKube version` command.

**Comment by mstrYoda** [comment]
Output of the command is "BotKube version: v0.8.0"

**Comment by PrasadG193** [comment]
@mstrYoda I think this is already fixed in develop branch. Could you please try deploying BotKube with latest image. You can use the following command to use latest help chart
```bash
$ helm repo add infracloudio https://infracloudio.github.io/charts
$ helm repo update
$ helm install  --version v9.99.9-dev --name botkube --namespace botkube \
--set config.communications.slack.enabled=true \
--set config.communications.slack.channel=<SLACK_CHANNEL_NAME> \
--set config.communications.slack.token=<SLACK_API_TOKEN_FOR_THE_BOT> \
--set config.settings.clustername=<CLUSTER_NAME> \
--set config.settings.allowkubectl=<ALLOW_KUBECTL> \
--set image.repository=infracloud/botkube \
--set image.tag=latest \
infracloudio/botkube
```

**Comment by PrasadG193** [comment]
@mstrYoda Please let us know if you see the problem in develop branch also

**Comment by mstrYoda** [comment]
I've deployed botkube into our dev environment with specified configuration above. I will update my observation here when I deploy to production.

**Comment by mstrYoda** [comment]
I've tested it and observed that no longer get duplicate events.
