### ISSUE TITLE
Expose prometheus metrics for BotKube

### ISSUE THREAD

**Issue by sanketsudake** [infracloudio/botkube#182]
**Is your feature request related to a problem? Please describe.**
We should expose different  metrics from BotKube.
Eg. No of resources scanned, no of events sent to communication channels. etc.

**Describe the solution you'd like**
1. These metrics can be displayed using @BotKube metrics
2. Expose these metrics to prometheus so that user can  build his dashboards in Grafana based on BotKube metrics.

**Comment by PrasadG193** [comment]
Ref: https://prometheus.io/docs/guides/go-application/

**Comment by PrasadG193** [comment]
Fixed with https://github.com/infracloudio/botkube/pull/219
