### ISSUE TITLE
[ERROR] unmarshal error from configmap.yaml

### ISSUE THREAD

**Issue by daegeun-ha** [infracloudio/botkube#194]
There is an error from configmap.yaml, line number 184
after 'namespaces', neither include nor ignore isn't appear.
Maybe it is changed like below
---------------------------------------
namesapces:
  include:
    -all
  ignore:
    -

**Comment by sanketsudake** [comment]
@daegeun-ha  Please include your configmap.yaml complete contents ?

**Comment by PrasadG193** [comment]
@daegeun-ha Please make sure you are using the latest helm chart and image: `infracloudio/botkube:latest`
https://github.com/infracloudio/botkube/tree/develop/helm/botkube

**Comment by daegeun-ha** [comment]
Hello, Thank you for fast reply :)
@PrasadG193 latest helm chart also has the same problem
@sanketsudake my configmap.yaml is same as the original.
https://github.com/infracloudio/botkube/blob/develop/helm/botkube/values.yaml
problem line numbers are 183, 184

**Comment by PrasadG193** [comment]
Aah, I think we missed this while refactoring. 

Correct format is:
```
    - name: clusterrole
      namespaces:
        include:
          - all
      events:
        - create
        - delete
        - error
```
I am assuming you are getting this error while executing `@Botkube notifier configmap`

@daegeun-ha Please feel free to make this change and raise a PR
