### ISSUE TITLE
Add support to monitor custom resources

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#200]
**Is your feature request related to a problem? Please describe.**
BotKube should monitor custom resources and report about their status in case of failures/success. 

**Describe the solution you'd like**
Initial thoughts about the implementation:
We can create a CRD to register custom resource watcher
OR
Figure out a way to pass it through the BotKube config

**Comment by PrasadG193** [comment]
Another approach is to use dynamic informers https://www.firehydrant.io/blog/dynamic-kubernetes-informers/

**Comment by AmitKumarDas** [comment]
@PrasadG193 have you evaluated [metacontroller](https://metacontroller.app) for this?

**Comment by PrasadG193** [comment]
@AmitKumarDas No, let me take a look. Thanks. 
But my first level thought is to use dynamic client and dynamic informers and make the current implementation more generic to support any K8s resource.

**Comment by mshivanna** [comment]
similar to velero backups we can also monitor other custom resources like externalsecrets

```
    - name: kubernetes-client.io/v1/externalsecrets
      namespaces:
       include:
         - all
      events:
        - create
        - update
        - delete
        - error
      updateSetting:
        includeDiff: true
        fields:
          - status.status
