### ISSUE TITLE
[BUG] Failed to list *v1beta1.Ingress: the server could not find the requested resources

### ISSUE THREAD

**Issue by daegeun-ha** [infracloudio/botkube#204]
**Describe the bug**
When we get logs from running botkube pod, the error msg('E1018 06:30:18.211393       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20190918160344-1fbdaa4c8d90/tools/cache/reflector.go:96: Failed to list *v1beta1.Ingress: the server could not find the requested resource') is repeated infinitely.

I think it is some problem of version difference. Because I saw related news about this. (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)
Now our kubernetes version is: 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

How can I fix it?
**To Reproduce**

**Expected behavior**

**Screenshots**
![v1beta1 ingress error](https://user-images.githubusercontent.com/37510916/67071397-61986100-f1bd-11e9-84b5-bb72d325dfc5.png)

**Additional context**
Because we are running global kubernetes cluster, now I cannot upgrade version of the kubernetes.. I think it it'll be nice if I can change some library in codes.

**Comment by PrasadG193** [comment]
@daegeun-ha as you know, after K8s 1.16, `extensions` apigroup is no longer valid. You should be migrating your resource specs to use correct apigroup.
Now coming back to error you are seeing in the logs, we have already added `Prerequisites` on the installation page. https://www.botkube.io/installation/

```
Prerequisites:
- Kubernetes 1.14 or higher is recommended
- For Kubernetes < 1.14, BotKube won’t be able to monitor Ingress resources
```
Since the endpoint of the Ingress resource has been changed, it needs at least K8s v1.14 version to work. This error has nothing to do with other functionalities, you can still monitor other resources. You can ignore this message or remove `ingress` resource from BotKube configuration.  
We are planning to use dynamic informers in the next release. But not sure if that will solve the problem.

**Comment by daegeun-ha** [comment]
Thank you for reply. However, after I removed ingress resource from BotKube configuration, error msgs still appear. 
![no ingress](https://user-images.githubusercontent.com/37510916/67072578-25b2cb00-f1c0-11e9-8f93-5cf289d32972.png)
(There is no informer of ingress)
Is there another something I can do for it?

**Comment by PrasadG193** [comment]
What error do you see after removing ingress from the configuration?

**Comment by daegeun-ha** [comment]
Same errors are printed

**Comment by daegeun-ha** [comment]
Oh, now I got it.
After remove 'ingress' key and value from ResourceInformerMap (/pkg/utils/utils.go), error msgs don't appear now. Thank you for kind replies. :)

**Comment by PrasadG193** [comment]
The recommended fix would be to upgrade your cluster (for security and other reasons)

If you still want to use older apigroups, the hackish fix would be to revert this change: https://github.com/infracloudio/botkube/commit/8835dea14463e8d9110c17a1892704759f5e2b9f#diff-fb81b0a96eed5b010cfb081b3aef4431L106

**Comment by daegeun-ha** [comment]
Thank you, I'll try it!

**Comment by daegeun-ha** [comment]
It'll be great I can upgrade the cluster, but I'm just a new person on this company. By the way, your suggestion works well. Thank you again!
