### ISSUE TITLE
Aggregate pod status to reduce notification noise

### ISSUE THREAD

**Issue by nabadger** [infracloudio/botkube#212]
**Is your feature request related to a problem? Please describe.**

I find that most solutions in this area including (including botkube) do not provide the ability to rollup events.

Ideally I want to know at the Deployment level whether a rollout was successful or not. However, for this to work, you need to understand what the pods are doing, and then aggregate results back up.

My issue is that numerous services may have many pods (10, 50, 100...) - typically during a deployment, if you get a pod error, it's most likely going to affect all pods (poor configuration, application bug, etc). This results in a lot of notifications being sent (and would put me off enabling events at the pod-level, although it's the only option at the moment).

**Describe the solution you'd like**

An additional option at the deployment/statefulset level that can:

- Give the overall status of a deployment
- OnError, provide some context about what happened (usually grabbing details from the Pod)
  - We already have this on the pod-event, so it would mean using the same information
  - Also, if we could get Pod logs (maybe just from the first pod that errors?), that would be awesome
- The goal would be to minimize the number of notifications sent

**Comment by PrasadG193** [comment]
Hey @nabadger,
I think, part of this issue is being covered in https://github.com/infracloudio/botkube/issues/203. Could you please have a look and let me know if you have any suggestion. Please update the description accordingly.

**Comment by PrasadG193** [comment]
I believe this is already addressed with #203. Please feel free to reopen if it doesn't solve your use case.
