### ISSUE TITLE
Investigate Helm V3 support

### ISSUE THREAD

**Issue by sanketsudake** [infracloudio/botkube#214]
**Is your feature request related to a problem? Please describe.**
Recently Helm v3 was released. We should investigate how we can leverage Helm v3 recent features and any compatibility changes required in BotKube

**Additional context**
Helm V3
https://v3.helm.sh/docs/

**Comment by gmkumar2005** [comment]
I have used helm3 to deploy this package on OpenShift 4. So I think current code base is compatible. Is there any specific feature of Helm3  which is needed ?

**Comment by vishal-biyani** [comment]
@gmkumar2005 Thanks for confirming - this issue was just to validate and document if any changes needed for Helm3

**Comment by PrasadG193** [comment]
This issue isn't relevant anymore. We have documented both the ways - with helm2 and helm3 - to install BotKube. https://www.botkube.io/installation/slack/
