### ISSUE TITLE
Propogate context and remove global variables usage

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#220]
- Create a context in main() and propagate over the function calls. 
- Set timout in context while calling go routines to avoid fragmentation

**Comment by pkosiec** [comment]
Additional scope (moved from #589):
    - Do not use global variables defined in `utils.go`, `filterengine/global.go` etc., they need to be converted to local
    - Use local logger instance passed via reference to all components
        - It can be replaced in tests to make sure it is disabled 
    -  Errors should be more often returned from functions, e.g. https://github.com/infracloudio/botkube/blob/a48b8276a0e0bbcb691667070df4419a6084656b/pkg/bot/discord.go#L69
        - Partially fixed #593
