### ISSUE TITLE
[BUG] BotKube redundant error messages when deployed in multicluster

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#230]
**Describe the bug**
When BotKube is deployed in multiple cluster with `settings.allowkubectl:false` set in the config, it returns redundant error messages when `BotKube` commands are executed.

Sample messages (provided by an user on BotKube slack)
```
Sorry, the admin hasn't given me the permission to execute kubectl command on cluster 'cluster-0hyv0'.
Sorry, the admin hasn't given me the permission to execute kubectl command on cluster 'cluster-0253f'.
Sorry, the admin hasn't given me the permission to execute kubectl command on cluster 'cluster-6toxk'.
Sorry, the admin hasn't given me the permission to execute kubectl command on cluster 'cluster-08cka'.
Cluster: cluster-mx8ae
No resources found in default namespace.
```

**To Reproduce**
1. Deploy BotKube on multiple clusters with the same token
2. Execute `@BotKube get pods` command

**Expected behavior**
BotKube should get response only from the cluster which is configured for the channel or whose name is passed with `--cluster-name` flag

**Comment by mbtamuli** [comment]
I would like to work on this issue.

**Comment by mbtamuli** [comment]
I'm not able to work on this for now. If no one takes this up, I'll look at it again.

**Comment by PrasadG193** [comment]
Fixed with https://github.com/infracloudio/botkube/pull/243
