### ISSUE TITLE
Option to restrict BotKube command execution only from configured channel

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#235]
**Is your feature request related to a problem? Please describe.**
Right now, BotKube commands can be executed from any channel or in DM to BotKube. Based on feedback, there are use cases where people want to restrict `@BotKube` command execution from configured (private) channel only.
  
**Describe the solution you'd like**
We should add a flag in config `settings` which allows @BotKube command execution from the configured channels only. When BotKube is configured with such flag and somebody executed command from outside the channel, user should get response that command execution is restricted.

**Comment by mahendrabagul** [comment]
I have started to work on this. WIP
