### ISSUE TITLE
[BUG] Helm instructions not available

### ISSUE THREAD

**Issue by RSijelmass** [infracloudio/botkube#236]
**Describe the bug**
For any new contributors, the [CONTRIBUTING.md](https://github.com/infracloudio/botkube/blob/develop/CONTRIBUTING.md) file goes through a detailed step-by-step to get the project set up on everyone's local machine. One can decide to run the project locally, or through docker. In the latter, however, a reference is made to the [README.md](https://github.com/infracloudio/botkube#using-helm) on how to use `helm`. 

This, however, seems to be removed. The link is also referencing to a header `#using-helm`, which does not exist in the README. Now the docker setup can't easily be completed by anyone joining the project.

**To Reproduce**
1. Go to [CONTRIBUTING.md](https://github.com/infracloudio/botkube/blob/develop/CONTRIBUTING.md#build-the-container-image)
2. pass through to [the link provided](https://github.com/infracloudio/botkube#using-helm).
3. Notice the lack of information given

**Expected behavior**
Either add the setup and complete usage of `helm` directly on the CONTRIBUTING.md, or reinstate it in the README.md.

**Comment by PrasadG193** [comment]
Hi @RSijelmass,
Thanks for reporting this. The instructions in CONTRIBUTING.md seem to be outdated. I'll update it ASAP.

**Comment by PrasadG193** [comment]
Hey @RSijelmass ,
We have updated the [CONTRIBUTING.md](https://github.com/infracloudio/botkube/blob/develop/CONTRIBUTING.md) as per the latest changes. Please let us know if you still face any issue
