### ISSUE TITLE
[BUG] ConfigMap in repo doesn't match actual file in Helm chart

### ISSUE THREAD

**Issue by alpha-er** [infracloudio/botkube#241]
The key `config.yaml` in the packaged chart doesn't match the one in [source code](https://github.com/infracloudio/botkube/blob/develop/helm/botkube/templates/configmap.yaml#L11) which is `resource_config.yaml`.

From packaged chart:
```
→ helm fetch --untar https://infracloudio.github.io/charts/botkube-v0.9.1.tgz
→ cat botkube/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "botkube.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |
  {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

**Comment by PrasadG193** [comment]
Hey @alpha-er,
You are comparing wrong helm chart. Helm chart with “v0.9.1” holds artifacts for the latest stable release i.e v0.9.1. If you want helm chart for “develop” branch, please use “v9.99.9-dev” helm chart version.

**Comment by PrasadG193** [comment]
Please check Contributing doc for more info: https://github.com/infracloudio/botkube/blob/develop/CONTRIBUTING.md#build-the-container-image

**Comment by alpha-er** [comment]
@PrasadG193, right. So, should I override the `image.tag` in the values file instead of `latest`? Because I just did a straightforward `helm install` of `v0.9.1` and the pod is in a `CrashBackoffLoop` with the error:
```
FATA[2020-01-17T02:56:40Z] Error in loading configuration. Error:open /config/resource_config.yaml: no such file or directory
```

**Comment by PrasadG193** [comment]
Yes. You need to set image tag as `image.tag=v0.9.1` if you are using `v0.9.1` helm chart. Please see: https://www.botkube.io/installation/slack/#h-install-BotKube-k8s
