### ISSUE TITLE
[BUG] MatterMost getUser call is causing index out of range exception

### ISSUE THREAD

**Issue by rivu007** [infracloudio/botkube#245]
As per the documentation, MatterMost integration is not working. After providing the details in values.yml, deploying the helm chart is causing the pods in `CrashLoopBackOff` status.

1. Please proceed with the MatterMost integration as described here: https://www.botkube.io/installation/mattermost/
2. Set the logLevel to `INFO`
3. Deploy the helm chart in kubernetes cluster v 1.15.4
4. Check the status of the pod and grep the console log.

**Versions**
MatterMost: v5.9.8
Kubernetes: v1.15.4
Botkube: v0.9.1

**Expected behavior**
The pod should be in `Running` status.

**Screenshots**
![MatterMost](https://user-images.githubusercontent.com/5902213/74285508-4cc07a00-4d26-11ea-99ca-5c58ecb5e6fc.png)

**Console Log**
```
INFO[2020-02-11T22:15:20Z] BotKube connected to Mattermost!             
INFO[2020-02-11T22:15:20Z] Registering watcher on configfile /config/config.yaml 
panic: runtime error: index out of range

goroutine 11 [running]:
github.com/infracloudio/botkube/pkg/bot.MMBot.getUser(0xc00036a5c0, 0x1a, 0xc00033d320, 0x4, 0xc00033d2d0, 0x6, 0xc00033d778, 0x3, 0x1, 0xc00036a620, ...)
	/app/pkg/bot/mattermost.go:193 +0x191
github.com/infracloudio/botkube/pkg/bot.MMBot.listen(0xc00036a5c0, 0x1a, 0xc00033d320, 0x4, 0xc00033d2d0, 0x6, 0xc00033d778, 0x3, 0x1, 0xc00036a620, ...)
	/app/pkg/bot/mattermost.go:226 +0x252
github.com/infracloudio/botkube/pkg/bot.(*MMBot).Start.func1(0xc000241c00)
	/app/pkg/bot/mattermost.go:107 +0xf0
created by github.com/infracloudio/botkube/pkg/bot.(*MMBot).Start
	/app/pkg/bot/mattermost.go:95 +0x429
```

**Comment by hksk8s** [comment]
I would like to work on this issue

**Comment by mahendrabagul** [comment]
I would like to work on this issue

**Comment by jselleck** [comment]
Comments:  I noticed while reviewing this issue that "botkube" is set as a const for BotUser.  It would be nice if the user could be determined based on the token used OR if BotUser was an option in the config.   Our instance of Mattermost has tight restrictions on how users are created.  A user with the name of botkube is not feasible for us.

**Comment by PrasadG193** [comment]
We should make username configurable through a configuration

**Comment by PrasadG193** [comment]
@mahendrabagul Are you still working on this?

**Comment by mahendrabagul** [comment]
Yes, I will take care of this @PrasadG193
