### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by balavs2806** [infracloudio/botkube#251]
**Describe the bug**
I have configured botkube to send alerts and execute commands from my slack channel. The problem now is I am able to get a notification on events changes, but when I type @BotKube ping command from slack channel am not able to get any responses(even any kubectl commands).

.

**Comment by PrasadG193** [comment]
@balavs2806 Can you please post communication setting in config here (please make sure you remove token information before)?

**Comment by balavs2806** [comment]
@PrasadG193 Here is the communication settings in my config

    communications:
      # Settings for Slack
      slack:
        enabled: true
        channel: 'test-alerts'
        token: '####################################'
        notiftype: long                         # Change notification type short/long you want to receive. notiftype is optional and Default notification type is short (if not specified)

      # Settings for Mattermost
      mattermost:
        enabled: false
        url: 'MATTERMOST_SERVER_URL'                # URL where Mattermost is running. e.g https://example.com:9243
        token: 'MATTERMOST_TOKEN'                   # Personal Access token generated by BotKube user
        team: 'MATTERMOST_TEAM'                     # Mattermost Team to configure with BotKube
        channel: 'MATTERMOST_CHANNEL'               # Mattermost Channel for receiving BotKube alerts
        notiftype: short                            # Change notification type short/long you want to receive. notiftype is optional and Default notification type is short (if not specified)

      # Settings for ELS
      elasticsearch:
        enable: false
        server: 'ELASTICSEARCH_ADDRESS'              # e.g https://example.com:9243
        username: 'ELASTICSEARCH_USERNAME'
        password: 'ELASTICSEARCH_PASSWORD'
        # ELS index settings
        index:
          name: botkube
          type: botkube-event
          shards: 1
          replicas: 0

      # Settings for Webhook
      webhook:
        enabled: false
        url: 'WEBHOOK_URL'                          # e.g https://example.com:80

    # Setting to support multiple clusters
    settings:
      # Cluster name to differentiate incoming messages
      clustername: dev
      # Set true to enable kubectl commands execution
      allowkubectl: true
      # Set true to enable config watcher
      configwatcher: true
      # Set false to disable upgrade notification
      upgradeNotifier: true

**Comment by PrasadG193** [comment]
Do you see any error logs in the BotKube pod?
