### ISSUE TITLE
Don't use latest in helm image tag

### ISSUE THREAD

**Issue by eddycharly** [infracloudio/botkube#257]
https://github.com/infracloudio/botkube/blob/16e90962d65b27d874f0a5129e9f42e25d793aeb/helm/botkube/values.yaml#L12

Having latest in helm image tag is dangerous, it breaks with current latest image because of a change in the config yaml file.

**Comment by PrasadG193** [comment]
Hey @eddycharly,
`develop` branch contains latest changes under development. So one is not expected to deploy BotKube from `develop` unless they want to experiment and test changes under development. Ideally, as described in docs (https://www.botkube.io/installation/), one should refer latest release or master branch for development. The helm charts and deploy manifest we have in `develop` are compatible with latest changes i.e ":latest" branch only. Once we do the release, we tag helm charts and images with the stable tag.

**Comment by eddycharly** [comment]
Hi @PrasadG193 , that's not true, the helm chart v0.9.1 is using `latest` (see https://github.com/infracloudio/botkube/releases/download/v0.9.1/helm-chart-botkube-v0.9.1.tgz), so deploying the chart doesn't work without changing the values.

**Comment by PrasadG193** [comment]
I see. If you are talking about default values, then you are right. We should update the release script to overwrite default image tag as well. Thanks

**Comment by eddycharly** [comment]
Fixed by #259
