### ISSUE TITLE
[BUG] Helm - indentation in clusterrole.yaml

### ISSUE THREAD

**Issue by OKyHb** [infracloudio/botkube#267]
When "podSecurityPolicy.enabled= true" I get this error with helm chart v0.10.0:

`Error: YAML parse error on botkube/templates/clusterrole.yaml: error converting YAML to JSON: yaml: line 18: did not find expected key`

**To Reproduce**
1. Set "podSecurityPolicy.enabled= true" in values.yaml
2. helm template -f values.yaml botkube infracloudio/botkube
3. Get error

**Additional context**
Could you please fix the indentation in clusterrole.yaml? Use "nindent 2" on the line 13th or move "podSecurityPolicy" block two spaces to the right.

**Comment by PrasadG193** [comment]
Hey @OKyHb,
Thanks for reporting this. Would it be possible for you to raise the PR to fix this? You already know the resolution :)
