### ISSUE TITLE
[BUG] Not receiving notifications on Slack, and ping does not work

### ISSUE THREAD

**Issue by sadortun** [infracloudio/botkube#275]
**Describe the bug**
Hi !

We have followed the instructions on how to install and configure botcube, but unfortunatly the bot is unresponsibe.

![image](https://user-images.githubusercontent.com/794449/80921952-b9f11380-8d47-11ea-9675-3c9bb5d6422f.png)

Looking at the logs, we can see a  lot of `not found` messages
![image](https://user-images.githubusercontent.com/794449/80921988-ffaddc00-8d47-11ea-8590-6f5b7c867818.png)

Also, is it normal that the bot is away ?
![image](https://user-images.githubusercontent.com/794449/80922058-88c51300-8d48-11ea-917e-79281890aed1.png)

**To Reproduce**
Installed with Helm2

```
helm upgrade  helm-botkube --namespace botkube \
  --set config.communications.slack.enabled=true \
  --set config.communications.slack.channel=k8s \
  --set config.communications.slack.token=xoxb-xxxxxxxxxxxxxxxxxxxxxxx  \
  --set config.settings.clustername=abcd \
  --set config.settings.allowkubectl=false \
  --set image.repository=infracloudio/botkube \
  infracloudio/botkube
```
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sadortun** [comment]
Tested with `deploy-all-in-one.yaml` and it working like a charm :) !

**Comment by PrasadG193** [comment]
That's a bug in documentation side. We have updated the helm3 commands but helm2 still pointing to older syntax. Let me fix it
