### ISSUE TITLE
Using conventional index name format 'index-%Y.%m.%d' in ElasticSearch configuration

### ISSUE THREAD

**Issue by tavisca-rkadikar** [infracloudio/botkube#283]
**Is your feature request related to a problem? Please describe.**
Yes. Currently, BotKube is supporting a fixed index for ElasticSearch configuration. For ease of log maintenance and restoring, an index should a tag or timestamp which can be useful for filtering them.

**Describe the solution you'd like**
Using conventional index name format 'index-%Y.%m.%d' will help to resolve the issue

**Comment by kartik-moolya** [comment]
Working on this
