### ISSUE TITLE
Ignore namespaces using regex

### ISSUE THREAD

**Issue by semoac** [infracloudio/botkube#295]
**Is your feature request related to a problem? Please describe.**

I want to ignore multiple namespaces using a wildcard like: `project-experimental-*`

**Describe the solution you'd like**

It would be awesome if we can specify labels or regex to ignore short-lived namespaces.

**Describe alternatives you've considered**

None.

**Additional context**

I try using `project-experimental`  hoping that `string.Contains`  will match but it didn't.

**Comment by PrasadG193** [comment]
This sounds good. We should definitely have this

**Comment by God-father1** [comment]
You could put \s* in between every character in your search string so if you were looking for cat you would use c\s*a\s*t\s*s\s*s.

**Comment by PrasadG193** [comment]
@God-father1 would you like to give a try?

**Comment by God-father1** [comment]
Sure

**Comment by jkremser** [comment]
I am also looking into this..
