### ISSUE TITLE
Webinar: Monitoring Kubernetes clusters by “chatting” with them audit

### ISSUE THREAD

**Issue by semoac** [infracloudio/botkube#296]
Hi!

These are paid features? Can't find them on the repository.

<img width="1222" alt="Screen Shot 2020-06-25 at 20 14 40" src="https://user-images.githubusercontent.com/20688668/85807975-8a480180-b721-11ea-8ea1-6e92dcc88c7b.png">

<img width="1218" alt="Screen Shot 2020-06-25 at 20 22 23" src="https://user-images.githubusercontent.com/20688668/85807990-9764f080-b721-11ea-9cc5-abe3e5d43159.png">

**Comment by PrasadG193** [comment]
Hey @semoac, 
As said, that is an alpha feature which is yet to be released.
We are yet to perform stress testing to make it more robust. The WIP PR can be found here: https://github.com/infracloudio/botkube/pull/292
