### ISSUE TITLE
Filter out pods by selector

### ISSUE THREAD

**Issue by bcouetil** [infracloudio/botkube#314]
**Describe the solution you'd like**

Is there a way to filter out some kind of pod that fails, but not all in the namespace ? A particular pod of mine has often a fail in readiness, I don't want to have notifications for it...

If it's possible using botkube filters, please provide an exemple :smile:

**Comment by PrasadG193** [comment]
Hey @bcouetil,
It is possible to filter notification for specific resources using annotations. Please check https://www.botkube.io/usage/#filter-events-using-annotations.

**Comment by bcouetil** [comment]
thank you for your quick response :heart: 

My bad, I did not think of this approach, so missed this part of documentation :sweat_smile:
