### ISSUE TITLE
Add Helm Chart to helm/charts stable/incubator repo?

### ISSUE THREAD

**Issue by adamhaney** [infracloudio/botkube#32]
Helm Operates a "stable" and "incubator" repository of charts that are included without any additional configuration to the helm command. It appears that all that would be required to have the helm chart in this repo included in the default repository would be to open a pull request to helm/charts (assuming there were no objections to the chart). If the chart was in the stable or incubator repositories it would eliminate the git checkout step from the installation process. 

I'd be happy to make a copy of the current state of the chart in this repo and make a PR from my fork of helm/charts but I thought I'd ask permission / guidance first.

**Comment by PrasadG193** [comment]
@sanketsudake we should add BotKube to the stable/incubator repo now

**Comment by mumrau** [comment]
This is irrelevant now and should be closed (ping @sanketsudake probably).
See https://github.com/infracloudio/charts.

I ended up here while looking for the place where the helm chart is now hosted.

**Comment by sanketsudake** [comment]
Closed issue as BotKube chart is now part of https://github.com/infracloudio/charts.
