### ISSUE TITLE
Add script to create and destroy KIND cluster

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#320]
**Describe the solution you'd like**

- Create a script to create and destroy KIND clusters which can be used to execute test and CD jobs
- Add `make` targets for the same.
- Script can be placed under `hacks` dir

**Comment by haardikdharma10** [comment]
Hey @PrasadG193, I'd like to help in solving this issue. However, I didn't get the second bullet point you have mentioned. Can you help me with it?

**Comment by PrasadG193** [comment]
Hi @haardikdharma10, 
I meant `Makefile`, sorry for the confusion. So basically we should add a [Makefile](https://github.com/infracloudio/botkube/blob/develop/Makefile) target e.g - `make create-kind` and `make destroy-kind` targets to create and destroy KIND cluster

**Comment by haardikdharma10** [comment]
Also, should I add 2 different scripts for each one of them or only one should work, for both creating and destroying?

**Comment by PrasadG193** [comment]
We can have 2 targets - create and delete in a single script. Something like - `./hack/kind.sh create` & `./hack/kind.sh delete`
Additionally good to have `help` target also e.g `./hack/kind.sh help` which should be the default target as well.
