### ISSUE TITLE
Can we have readme for helm charts 

### ISSUE THREAD

**Issue by abhisheks-infracloud** [infracloudio/botkube#327]
**Describe the solution you'd like**
it would be nice to have a readme for helm chart which describes about the values used by the helm chart? 

**Additional context**
Currently there are no installation steps mentioned in the repo other than Documentation. it will help anyone landing to this repository for botkube installation through helm chart.

**Comment by PrasadG193** [comment]
Thanks @abhisheks-infracloud for pointing out.
We are going to add documentations about helm options in botkube.io.
We can use something like https://github.com/norwoodj/helm-docs to automate this

**Comment by abhisheks-infracloud** [comment]
Yes, that would be great. Thanks!

**Comment by PrasadG193** [comment]
Helm install options are documented here: https://www.botkube.io/configuration/#helm-install-options

**Comment by abhisheks-infracloud** [comment]
Great..Thanks !!
