### ISSUE TITLE
Ability to exclude some pods based on label or name

### ISSUE THREAD

**Issue by mlewiarz** [infracloudio/botkube#329]
I want to monitor pods in some critical namespaces but in these namespaces we also have cronjobs which dumps db. 
Problem is we got alerts when pods of this cronjobs are created and deleted.
Dumps are not critical so we would like to exclude them from alers.

It would be nice to add some annotation to cronjob/job/deployment/daemonset/statefulset we don't want to get alerted, or add some regex or full name to exclude events when match.

```
      resources:
            - name: pod
              namespaces:
                include:
                  - ns1
                  - ns2
              events:
                - update
                - delete
                - create
                - error
             exclude:
               - db-dump
```

**Comment by PrasadG193** [comment]
Hey @mlewiarz ,
It is possible to ignore notifications for specific resources by adding annotations to it.
Please check: 
https://www.botkube.io/usage/#filter-events-using-annotations

**Comment by codenio** [comment]
can this be closed?

**Comment by mlewiarz** [comment]
Yes, now I only have to find a way to pass annotation from to pod CronJob -> Job -> Pod
