### ISSUE TITLE
Add e2e test for executing kubectl command on forbidden verbs and resources

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#350]
**Is your feature request related to a problem? Please describe.**

Missing kubectl command test coverage for negative test-cases

**Describe the solution you'd like**

BotKube can be configured to allow access to specific kubectl commands only - https://github.com/infracloudio/botkube/blob/develop/test/resource_config.yaml#L224

Add a test case to execute kubectl command on a forbidden resource and a verb.
Add the test cases in the table-driven test map https://github.com/infracloudio/botkube/blob/develop/test/e2e/command/kubectl.go#L46

**Comment by anoopmsivadas** [comment]
@PrasadG193 Can You assign me on this one as well

**Comment by PrasadG193** [comment]
Sure!

**Comment by anoopmsivadas** [comment]
Hi @PrasadG193 all i have to do is add one test case with a forbidden verb and a resource, right?

**Comment by PrasadG193** [comment]
Yes, that should suffice, we already have test coverage for command with allowed verbs/resources

**Comment by anoopmsivadas** [comment]
@PrasadG193  I'm adding 2 test cases one with a forbidden verb and forbidden resource, and another one with allowed verb and a forbidden resource. is that fine?

**Comment by PrasadG193** [comment]
Sounds good. Thanks, @anoopmsivadas
