### ISSUE TITLE
[BUG] Missing container resource section for helm chart under deployment.yaml file

### ISSUE THREAD

**Issue by ZaheerAhmedShaik** [infracloudio/botkube#352]
**Describe the bug**
The `deployment.yaml` definition file is missing a container `resources` section for CPU & Memory requests and limits to be overrided from the values.yaml, whereas `resources` section is passed in the values.yaml file

Missing resources section under `spec.template.spec.containers` here https://github.com/infracloudio/botkube/blob/master/helm/botkube/templates/deployment.yaml#L27

**Expected behavior**
`resources` section to be included under `spec.template.spec.containers` of `deployment.yaml` file for the same to be passed from `values.yaml` as defined here https://github.com/infracloudio/botkube/blob/master/helm/botkube/values.yaml#L290

**Comment by hairyhenderson** [comment]
This was fixed in #330 but there hasn't yet been a release containing that

**Comment by KarenEfereyan** [comment]
> This was fixed in #330 but there hasn't yet been a release containing that

Maybe a new issue requesting a release containing that could be opened? And I could work on it?

**Comment by PrasadG193** [comment]
We have published BotKube v0.11.0 release. Please use helm chart with version v0.11.0 for the latest changes
