### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by kichloo** [infracloudio/botkube#353]
Fix the typo errors in README.md and subsequently, update the documentation.

**Comment by kichloo** [comment]
The label can be changed from 'bug' to 'documentation'.
Also please assign this issue to me!

**Comment by PrasadG193** [comment]
Hey @kichloo, could you please elaborate more on what change you are asking in README?

**Comment by kichloo** [comment]
@PrasadG193 I wanted to fix the typos present in the README.md file

**Comment by kichloo** [comment]
@PrasadG193 Could you provide an update on this issue, because I did not know you removed the label.

**Comment by PrasadG193** [comment]
Hey @kichloo, can you please add more description about the issue? The current description doesn't make much sense

**Comment by kichloo** [comment]
@PrasadG193 Done. Now, please assign this issue.

**Comment by kichloo** [comment]
@PrasadG193 The changes which I wanted to implement are now already done by another user.
