### ISSUE TITLE
[BUG] e2e tests are flaky 

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#384]
**Describe the bug**

e2e tests on CI are failing for update events validate

See run history on master - e.g https://github.com/infracloudio/botkube/runs/1193896198

**Comment by A-kanksh-a** [comment]
@PrasadG193 e2e Tests are failing because update event validation goes through a series of create and update a resource, while validating the same from `lastseenmessage`, it gets the create operation result, instead of update sometimes and the tests fail.
Need to check on that.
