### ISSUE TITLE
defaultNamespace field in config won't work on changing to other than default

### ISSUE THREAD

**Issue by A-kanksh-a** [infracloudio/botkube#429]
**Describe the bug**
Botkube doesn't produce report of other namespace except default even if resource configuration is changed

**To Reproduce**
1. Go to 'resource_config.yaml'
2. Change the default namespace field other than default for ex- `botkube`
3. deploy botkube and then run the command `@Botkube get deployments` from the applications. 
4. It will show results of default namespace instead of showing result for `botkube` namespace which is set to be default

**Expected behavior**
The result expected should be resources listed in `botkube` namespace

**Screenshots**
![image](https://user-images.githubusercontent.com/41359156/98121750-b5174300-1ed5-11eb-928a-8a849424feed.png)

 Results after deploying botkube
![image](https://user-images.githubusercontent.com/41359156/98121905-ec85ef80-1ed5-11eb-8cb1-fced266dc67e.png)

**Additional context**
If -n flag is provided then the response is correct

**Comment by sgandon** [comment]
Indeed I have also noticed it and fixed it in a PR I am preparing for #421 .

**Comment by alexavrutin** [comment]
I also encountered this problem but in my case adding -n <namespace name> didn't help. The bot simply does not return anything if I specify -n. If I don't specify -n, it returns "No resources found..." Any ideas what might cause it?

**Comment by sgandon** [comment]
@alexavrutin to be sure about what you are doing, the `-n` shall be used to specify a namespace like `@botkube get pods -n default` where `default` is the namespace named `default`.
You can just use `-n` without any string following it.

**Comment by sramek5** [comment]
#458

**Comment by PrasadG193** [comment]
Fixed with: https://github.com/infracloudio/botkube/pull/459
