### ISSUE TITLE
Switch to github container registry to host BotKube container image

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#432]
**Is your feature request related to a problem? Please describe.**
Since docker hub has started applying rate limits on image pulls, better to switch to an alternate solution - GitHub container registry 
https://docs.github.com/en/free-pro-team@latest/packages/managing-container-images-with-github-container-registry/connecting-a-repository-to-a-container-image 

**Describe the solution you'd like**
This includes - 

- [x] Update make targets
- [x] Update CI job to push to correct registry
- [x] Update helm charts and deploy-all-in-one*.yamls to use correct registry
- [ ] Update README and CONTRIBUTING.md

**Comment by vaibhavp** [comment]
Hey @PrasadG193 , Please assign this to me. I would like to take this up

**Comment by PrasadG193** [comment]
Hey @vaibhavp are you still working on this?

**Comment by vaibhavp** [comment]
@PrasadG193 as per our discussion on slack it is pending for decision to move it or not on GitHub registry.

**Comment by PrasadG193** [comment]
@vaibhavp We had decided to go with GHCR. I think you missed the thread :slightly_smiling_face: . I'll tag you there

**Comment by onedr0p** [comment]
Any update on this?

**Comment by kartik-moolya** [comment]
Rather than switching I feel we should have it in gcr as well as dockerhub. wdyt @PrasadG193 ?
