### ISSUE TITLE
[BUG] Error message is not show the correct date in Slack

### ISSUE THREAD

**Issue by Kydybets** [infracloudio/botkube#435]
**Describe the bug**

When I got a message in slack about any Error the time is wrong

But when we got a message about Update or Create it show the right time

**To Reproduce**

**Expected behavior**
in the Error message, it show the correct name.

**Screenshots**

<img width="593" alt="Screenshot 2020-11-22 at 20 31 18" src="https://user-images.githubusercontent.com/27759761/99913812-66094480-2d02-11eb-99bc-861c71baa464.png">
<img width="713" alt="Screenshot 2020-11-22 at 20 31 11" src="https://user-images.githubusercontent.com/27759761/99913813-673a7180-2d02-11eb-875b-ad5c0a78611a.png">
<img width="705" alt="Screenshot 2020-11-22 at 20 31 26" src="https://user-images.githubusercontent.com/27759761/99913814-673a7180-2d02-11eb-96c2-c1976aa2caef.png">

**Additional context**

**Comment by hellozee** [comment]
Can't reproduce it with my setup. 
 - Does this happens all the time in your case? 
 - or happens once in a while? like while restarting botkube
 - or happens with that specific pod only?

**Comment by Kydybets** [comment]
@hellozee this is happens 
 - this is happening everytime;
 - it it happens in the different pods, we test it out in 4 clusters, the same behavior,
 
 we got this error simultaneously, 
 as for messages for update, create everything is correct.

**Comment by codenio** [comment]
@Kydybets, can you check the local time in your clusters.?

botkube uses `time.Now()` as timestamp as default and updates it in case of Create or Delete from the Object Metadata
https://github.com/infracloudio/botkube/blob/9f9d3725e3e7ce555fff023c7b96963e6026a602/pkg/events/events.go#L87-L101

**Comment by Kydybets** [comment]
Unfortunately, i can't check cause u don't have set-up environment

**Comment by Kydybets** [comment]
so i think we can close this for now
