### ISSUE TITLE
Robot function module

### ISSUE THREAD

**Issue by hehua2018** [infracloudio/botkube#436]
Hello! Can the robot code out, so that the robot function can do modular, convenient to do CI/CD, modular can handle API interface, thank you!

**Comment by vishal-biyani** [comment]
Hey @hehua2018 I am not really sure what is being requested here. Can you please elaborate a bit in detail? Please reopen the issue when adding more detail, I will close it for now.

**Comment by hehua2018** [comment]
I mean: can you start a robot project to do CI/CD
