### ISSUE TITLE
[BUG] Events not ignored in namespace despite having namespace in ignore for resources

### ISSUE THREAD

**Issue by darkhelmet** [infracloudio/botkube#450]
**Describe the bug**

I'm running botkube on our devops EKS (v1.18.9-eks-d1db3c) cluster which does CI. Jenkins creates things in the devops-jenkins-agents namespace. It does this a lot, and I don't need pod creation/deletion events for that namespace. I've added the namespace to ignore in the v1/pods resources section (that's the only change from the default install using the helm chart) and it still gives me notifications in my Slack channel.

**To Reproduce**

I have botkube installed to an EKS 1.18 cluster using the helm provider with the following config: https://gist.github.com/darkhelmet/9a61ecca6aaf7f4a4dd19ef0cfdccea0

**Expected behavior**

I expect botkube to ignore things for pods in the devops-jenkins-agents namespace

**Screenshots**

Config looks like it should ignore those events...

![Screen Shot 2021-01-21 at 3 17 37 PM](https://user-images.githubusercontent.com/36123/105401083-1fe63980-5bfc-11eb-930b-3ea7a29103a1.png)

But here they are...

![Screen Shot 2021-01-21 at 3 17 43 PM](https://user-images.githubusercontent.com/36123/105401088-21affd00-5bfc-11eb-91ef-11d29b60d710.png)

**Additional context**

I swear it worked at one point. I initially installed the chart via terraform, then manually edited the configmap. Pretty sure that worked. I didn't like that because it would break when I deployed again, so I wanted to render the values properly. I switched to this system, which results in a proper looking config file, everything runs, but despite the ignore being there it doesn't ignore.

**Comment by PrasadG193** [comment]
Duplicate issue: #419 
Fixed in v0.12.0
