### ISSUE TITLE
Default namespace key must be lowercase

### ISSUE THREAD

**Issue by rsaeba** [infracloudio/botkube#458]
Hi,
Defining a default namespace in helm/botkube/values.yaml with :
line 261 : defaultNamespace: "example"

The key must be in lowercase

**Comment by sramek5** [comment]
Agree! Found it using `@BotKube notifier showconfig`commnad.

**Comment by PrasadG193** [comment]
Fixed with: https://github.com/infracloudio/botkube/pull/459
