### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adityadoke** [infracloudio/botkube#460]
**Describe the bug**
My @BotKube is not working on my cluster  **charizard.alpha-sense.org** - its throwing invalid request error

```
botkube-579cfd7578-dmptr botkube INFO[2021-03-02T09:12:15Z] Invalid request. Dumping the response. Request:  get deployment --cluster-name <http://charizard.alpha-sense.org|charizard.alpha-sense.org> 
botkube-579cfd7578-dmptr botkube INFO[2021-03-02T09:13:57Z] Invalid request. Dumping the response. Request:  ping --cluster-name <http://charizard.alpha-sense.org|charizard.alpha-sense.org> 
botkube-579cfd7578-dmptr botkube INFO[2021-03-02T09:14:50Z] Invalid request. Dumping the response. Request:  commands list 
```

**To Reproduce**
1. Fire command through slack 

@BotKube commands list 

@BotKube get pods --cluster-name charizard.alpha-sense.org

@BotKube notifier status

@BotKube get deployment --cluster-name charizard.alpha-sense.org

```
botkube-579cfd7578-dmptr botkube INFO[2021-03-02T09:12:15Z] Invalid request. Dumping the response. Request:  get deployment --cluster-name <http://charizard.alpha-sense.org|charizard.alpha-sense.org> 
botkube-579cfd7578-dmptr botkube INFO[2021-03-02T09:13:57Z] Invalid request. Dumping the response. Request:  ping --cluster-name <http://charizard.alpha-sense.org|charizard.alpha-sense.org> 
botkube-579cfd7578-dmptr botkube INFO[2021-03-02T09:14:50Z] Invalid request. Dumping the response. Request:  commands list 
```

**Expected behavior**
Expected Command output is not coming in slack channel  
**Screenshots**

**Additional context**
It treats my cluster name as hyperlink even after removing hyperlink from slack format

**Comment by girishg4t** [comment]
@PrasadG193 i have added small logic to remove the unwanted string from clustername, i have tested that using slack but not with other channels, if the behavior is different then we can add separate method to resolve that
