### ISSUE TITLE
[FR] Official entry for Botkube in Artifact Hub

### ISSUE THREAD

**Issue by pierluigilenoci** [infracloudio/botkube#481]
**Is your feature request related to a problem? Please describe.**

To date there is only the unofficial chart from @ebrianne:

https://artifacthub.io/packages/helm/ebrianne/botkube

This chart deserve an official place there. 

**Describe the solution you'd like**

An official entry on Artifact Hub.

**Describe alternatives you've considered**

No alternative

**Comment by pierluigilenoci** [comment]
@PrasadG193 any news about this?

**Comment by pierluigilenoci** [comment]
@PrasadG193 @thijsdejong @vaibhavp could you please take a look?

**Comment by PrasadG193** [comment]
@pierluigilenoci I am adding this in upcoming release's roadmap

**Comment by PrasadG193** [comment]
The official chart is now listed on artifact hub https://artifacthub.io/packages/helm/infracloudio/botkube
