### ISSUE TITLE
Push Botkube container image to ECR Public Gallery

### ISSUE THREAD

**Issue by kartik-moolya** [infracloudio/botkube#496]
**Is your feature request related to a problem? Please describe.**
Pulling images from dockerhub might become problematic when someone reaches dockerhub rate limits

**Describe the solution you'd like**
We can also push the docker images to ECR public gallery simultaneously along with dockerhub

**Describe alternatives you've considered**
NA

**Additional context**
Pushing images to ECR public gallery would help customers using botkube on EKS or other AWS compute as pulling images from ECR same region is free of cost

**Comment by vaibhavp** [comment]
#432
