### ISSUE TITLE
[BUG] arm64: bad kubectl binary

### ISSUE THREAD

**Issue by disconn3ct** [infracloudio/botkube#516]
**Describe the bug**
Using `ghcr.io/infracloudio/botkube:v0.12.2`, commands on arm64 return `fork/exec /usr/local/bin/kubectl: exec format error`

**To Reproduce**
1. Install botkube on arm64
2. Send a command (`botkube cluster-info`)
3. See error: `fork/exec /usr/local/bin/kubectl: exec format error`

**Expected behavior**
Kubectl uses the correct architecture

**Screenshots**

**Additional context**

**Comment by PrasadG193** [comment]
@disconn3ct we can do a quick release if you could fix this. Please let me know if I can help
