### ISSUE TITLE
[CI] Add image vulnerability scan job in CI

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#549]
**Is your feature request related to a problem? Please describe.**

The latest released BotKube image has a few vulnerabilities. The report can be seen at artifacthub: https://artifacthub.io/packages/helm/infracloudio/botkube?modal=security-report

**Describe the solution you'd like**

We should -
- Fix the image vulnerabilities 
- And, add a CI check to catch such vulnerabilities early before publishing the release

**Comment by rahulii** [comment]
@PrasadG193 do we use gogo protobuf?

**Comment by PrasadG193** [comment]
Yes, we have that as an indirect dependency. I have upgraded the dep as per the report - https://github.com/infracloudio/botkube/pull/553
