### ISSUE TITLE
[FR] Allow the Chart to create extra manifest

### ISSUE THREAD

**Issue by pierluigilenoci** [infracloudio/botkube#561]
**Is your feature request related to a problem? Please describe.**
Sometimes, accessory to the installation there may be manifest to be installed (for example a SecretProviderClass).

**Describe the solution you'd like**
It would be nice to be able to do this directly via the Chart using the approach that ArgoCD also uses.

Ref: https://github.com/argoproj/argo-helm/blob/cf57a71a154a1a8a19f5f9d3980d60eb3efd80c8/charts/argo-cd/values.yaml#L62-L87

**Describe alternatives you've considered**
I don't think there are alternatives

**Comment by pierluigilenoci** [comment]
@ebrianne what do you think about it?

**Comment by pkosiec** [comment]
Hi @pierluigilenoci, I've implemented the feature in the PR #578 - hopefully it will be merged soon 🙂  Fingers crossed 🤞
