### ISSUE TITLE
Add Microsoft Teams suppport

### ISSUE THREAD

**Issue by sanketsudake** [infracloudio/botkube#60]
**Describe the solution you'd like**
We got a couple of requests for Microsoft Teams support at Kubernetes Days India. Need to explore possible integration.
https://products.office.com/en-US/microsoft-teams/group-chat-software

**Comment by aananthraj** [comment]
I would like to add a few points here

Tried some experimentation on this and understood that 
> Teams works differently in that if you want to talk to a bot, you must explicitly @ mention it. Teams will then POST the message to a public endpoint that the bot exposes. You then receive/authenticate the message and respond appropriately. It's a pretty differently workflow.
(views from github.com/poshbotio/PoshBot/ issues 68)

are we planning to implement the same?

for now, we could send event notifications through `incoming webhooks` in MsTeams.
creating a PR for the same.

**Comment by bitva77** [comment]
Just want to say that Teams support would be huge for us and likely many other companies forced into Teams. 

That's all  :)
