### ISSUE TITLE
[maintenance] Deprecate master branch

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#613]
**Is your feature request related to a problem? Please describe.**

As per the existing branch management procedure, `master` points to the stable revision, and `develop` points to the development revision of the source code. This adds an additional overhead of force-pushing to `master` branch after every release. The stable rev can always be found by checking out the release tag.

**Describe the solution you'd like**

For better management, 
1. We can treat `master` as a development copy and make it the default branch. Deprecate `develop`
2. Or deprecate `master`

**Comment by pkosiec** [comment]
Hi @PrasadG193,
In #594 there's a dedicated "to-do" to switch to the lighter GitHub flow, with additional release branches 🙂 We could close this issue as a duplicate. Let me know what you think! 🙂

**Comment by PrasadG193** [comment]
Great! Let's close this issue
