### ISSUE TITLE
Add Skip field BotKube Event 

### ISSUE THREAD

**Issue by ssudake21** [infracloudio/botkube#63]
**Describe the bug**
We need to add Skip field in BotKube struct so that if any of filters ask to skip the reporting of the event to slack, we should be able to that.
Filter Engine should not pass event further if it observes Skip fieldset.

**Expected behaviour**
Filter sets Skip field in BotKube Struct, FilterEngine should stop processing event.

**Additional context**
We had a use case where a BotKube user reported a lot of pods where getting created through CronJob and he was not interested in Create/Delete events for them. The filter could not allow skipping of events currently.

**Comment by PrasadG193** [comment]
Fixed with https://github.com/infracloudio/botkube/pull/67
