### ISSUE TITLE
[BUG] Fresh deploy in Kubernetes 1.14.1 not working

### ISSUE THREAD

**Issue by malozanoff** [infracloudio/botkube#85]
**Describe the bug**
Installed Slack App in a channel, ran the kubernetes deploy both via kubectl apply and helm (same issue), the bot is in the channel, it sends notifications, it responds to ping but does not respond to any other command.

A look at the logs from the backend pod shows:
`INFO[2019-04-30T18:49:54Z] Invalid request. Dumping the response`

**To Reproduce**
1. Follow installation instructions using a Kubernetes 1.14.1 cluster
2. Try to do a `@BotKube get pods`

**Expected behavior**
Expected the bot respond with something.

**Screenshots**
![image](https://user-images.githubusercontent.com/29872998/56991058-26ea3000-6b6d-11e9-9f85-ac121e671fb1.png)

**Additional context**
Kubernetes 1.14.1 cluster running in bare metal. Private Slack team

**Comment by PrasadG193** [comment]
Hi @malozanoff ,
I tried to reproduce the issue with BotKube v0.7.0 and K8s v1.14.1 on minikube. I didn't find any issue while executing any commands. I am passing `--set config.communications.slack.channel=alerts` where `alerts` is a private channel and I have already invited BotKube on that channel. Could you please tell me, what channel name you are using (i.e format of channel name)? Also, could you please send the content of configmap `botkube-configmap` in botkube namespace?

Thanks.

**Comment by PrasadG193** [comment]
Turned out to be a configuration problem. Hence closing the issue.
