### ISSUE TITLE
Include job status (succeeded/failed) with notification

### ISSUE THREAD

**Issue by vitobotta** [infracloudio/botkube#95]
**Is your feature request related to a problem? Please describe.**
Hi, I am trying BotKube but I am not sure if this is already possible. I would like to receive notifications when jobs are completed, including the status, so that I know whether the job failed or succeeded. This is particularly useful for scheduled backups.

**Describe the solution you'd like**
From what I can see, at the moment I receive a notification when a job is created, but I don't receive a notification when the job is completed that includes the status, so I would have to manually check if the job failed with kubectl. Also if I enable kubectl support for BotKube, commands like describing a pod or job don't seem to work. I get back `Command not supported. Please run /botkubehelp to see supported commands.`

**Describe alternatives you've considered**
The only alternative I know about is Kubewatch, but that also doesn't report the status of a completed job.

Thanks in advance!

**Comment by PrasadG193** [comment]
Hi @vitobotta ,

> Also if I enable kubectl support for BotKube, commands like describing a pod or job don't seem to work. I get back Command not supported. Please run /botkubehelp to see supported commands.

Can you please let me know what command format you are using?
