### ISSUE TITLE
Add support for Discordapp

### ISSUE THREAD

**Issue by kingdevnl** [infracloudio/botkube#97]
**Is your feature request related to a problem? Please describe.**
It would be nice if we can get support for discordapp.com
There is no software like this out there that has support for discord.
There are plenty of API Wrappers for discord out there
(Link to a wrapper for golang:) https://github.com/bwmarrin/discordgo

**Describe the solution you'd like**
Discord has a rich API and Role based secrurity (Eg limiting who can send/read/see channels etc.)

**Additional context**
discordapp.com
https://discordapp.com/developers/applications/

**Comment by aananthraj** [comment]
Discord go api clinet Ref : https://bwmarrin.github.io/discordgo/

**Comment by kingdevnl** [comment]
@codenio Could you implement discord support?,
I don't know anything about golang :(

**Comment by MustafaSaber** [comment]
any news here?

**Comment by kingdevnl** [comment]
Nope sadly

**Comment by codenio** [comment]
@kingdevnl sorry about this.

creating the Integration test for Discordapp is the hardest part than actually implementing the functionality. 

let me try my level best. it might take time.

**Comment by PrasadG193** [comment]
@codenio Please feel free to ping me if you need any help. We can also work together in adding integration test. Thanks for picking this up :)

**Comment by codenio** [comment]
@PrasadG193 thanks for the support.
yes, we could try together as earlier.

**Comment by kingdevnl** [comment]
Any new info about this?

**Comment by codenio** [comment]
> I'm wondering how much work it would be to implement it all, Hahahaha

@kingdevnl, when you can't help yourself. you have to wait for the community to respond to your requests.
